name: unihub_staff
description: UniHub Staff Check-in App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  connectivity_plus: ^5.0.1
  mobile_scanner: ^3.5.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  uuid: ^4.1.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
